name: Gerar Executável

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências Python
        run: |
          pip install pypdf selenium>=4.10.0 pyperclip pyinstaller pdfplumber

      # Baixar o EdgeDriver (versão fixa compatível com o Edge corporativo)
      - name: Baixar o EdgeDriver
        shell: pwsh
        run: |
          $version = "146.0.3856.62"
          $url = "https://msedgedriver.azureedge.net/$version/edgedriver_win64.zip"
          Invoke-WebRequest -Uri $url -OutFile edgedriver.zip
          Expand-Archive -Path edgedriver.zip -DestinationPath . -Force

      - name: Gerar o .exe limpo e independente
        run: |
          pyinstaller --onefile --noconsole --name "RoboFiscalizacao" --collect-all selenium --collect-all pdfplumber --add-data "msedgedriver.exe;." robo_brave-v1.py

      - name: Disponibilizar o .exe para download
        uses: actions/upload-artifact@v4
        with:
          name: RoboFiscalizacao
          path: dist/RoboFiscalizacao.exe
